development:
  adapter: postgresql
  database: earning_credit_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: earning_credit_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: earning_credit
  pool: 5
  timeout: 5000
